# Generated by Django 2.1.5 on 2019-02-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120)),
            ],
        ),
    ]
