# Generated by Django 2.1.5 on 2019-02-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190204_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email2',
            field=models.CharField(default='', max_length=140, unique=True),
            preserve_default=False,
        ),
    ]
