# Generated by Django 2.1.5 on 2019-02-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userinfo_email2'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('username2', models.CharField(max_length=120)),
                ('username3', models.CharField(max_length=120)),
            ],
        ),
    ]
